// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void StartAnimation_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_EntranceScreen
void ui_EntranceScreen_screen_init(void);
lv_obj_t * ui_EntranceScreen;
void ui_event_btnCount(lv_event_t * e);
lv_obj_t * ui_btnCount;
lv_obj_t * ui_lblButton;
void ui_event_configWifi(lv_event_t * e);
lv_obj_t * ui_configWifi;
lv_obj_t * ui_lblButton2;
void ui_event_calibrateProbePageButton(lv_event_t * e);
lv_obj_t * ui_calibrateProbePageButton;
lv_obj_t * ui_calibrateProbeButtonLabel;


// SCREEN: ui_CalibratePhScreen
void ui_CalibratePhScreen_screen_init(void);
lv_obj_t * ui_CalibratePhScreen;
void ui_event_highPointCalButton(lv_event_t * e);
lv_obj_t * ui_highPointCalButton;
lv_obj_t * ui_highPointCalLabel;
void ui_event_lowPointCalButton(lv_event_t * e);
lv_obj_t * ui_lowPointCalButton;
lv_obj_t * ui_lowPointCalLabel;
void ui_event_midPointCalButton(lv_event_t * e);
lv_obj_t * ui_midPointCalButton;
lv_obj_t * ui_midPointCalLabel;
void ui_event_beginCalButton(lv_event_t * e);
lv_obj_t * ui_beginCalButton;
lv_obj_t * ui_beginCalLabel;
lv_obj_t * ui_calibrationLabel;


// SCREEN: ui_configWifiScreen
void ui_configWifiScreen_screen_init(void);
lv_obj_t * ui_configWifiScreen;
lv_obj_t * ui_ssidLabelName;
void ui_event_passwordTextArea(lv_event_t * e);
lv_obj_t * ui_passwordTextArea;
lv_obj_t * ui_passLabelName;
void ui_event_Keyboard(lv_event_t * e);
lv_obj_t * ui_Keyboard;
void ui_event_setWifiInfoButton(lv_event_t * e);
lv_obj_t * ui_setWifiInfoButton;
lv_obj_t * ui_wifiTestButtonLabel;
lv_obj_t * ui_wifiChooserDropdown;
void ui_event_RefreshScan(lv_event_t * e);
lv_obj_t * ui_RefreshScan;
lv_obj_t * ui_Label2;


// SCREEN: ui_PHReaderMainScreen
void ui_PHReaderMainScreen_screen_init(void);
lv_obj_t * ui_PHReaderMainScreen;
lv_obj_t * ui_mainTabView;
lv_obj_t * ui_pHReader;
lv_obj_t * ui_celciusSwitchLabel;
lv_obj_t * ui_fahrenheitSwitchLabel;
void ui_event_tempUnitsSwitch(lv_event_t * e);
lv_obj_t * ui_tempUnitsSwitch;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_tempStaticLabel;
lv_obj_t * ui_pHValLabel;
lv_obj_t * ui_PHStaticLabel;
lv_obj_t * ui_tempValLabel;
void ui_event_ReturnToHomeButton(lv_event_t * e);
lv_obj_t * ui_ReturnToHomeButton;
lv_obj_t * ui_Label5;
void ui_event_TurnOffScreenButton(lv_event_t * e);
lv_obj_t * ui_TurnOffScreenButton;
lv_obj_t * ui_Label4;
lv_obj_t * ui_chartTabPage;
lv_obj_t * ui_pHTempChart;
lv_obj_t * ui_showPHButton;
lv_obj_t * ui_Label10;
lv_obj_t * ui_showTempButton;
lv_obj_t * ui_Label13;
lv_obj_t * ui_settingsTabPage;
void ui_event_startWebpageButton(lv_event_t * e);
lv_obj_t * ui_startWebpageButton;
lv_obj_t * ui_startWiFiButtonLabel;
void ui_event_plotTimePeriodDropdown(lv_event_t * e);
lv_obj_t * ui_plotTimePeriodDropdown;
lv_obj_t * ui_plotTimePeriodLabel;
void ui_event_samplingIntervalDropdown(lv_event_t * e);
lv_obj_t * ui_samplingIntervalDropdown;
lv_obj_t * ui_samplingIntervalLabel;
lv_obj_t * ui_warningLabel;
void ui_event_startBluetoothButton(lv_event_t * e);
lv_obj_t * ui_startBluetoothButton;
lv_obj_t * ui_startBluetoothButtonLabel;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Label9;


// SCREEN: ui_APorSTAScreen
void ui_APorSTAScreen_screen_init(void);
lv_obj_t * ui_APorSTAScreen;
void ui_event_apMode(lv_event_t * e);
lv_obj_t * ui_apMode;
lv_obj_t * ui_Label1;
void ui_event_staMode(lv_event_t * e);
lv_obj_t * ui_staMode;
lv_obj_t * ui_Label3;


// SCREEN: ui_wifiTestScreen
void ui_wifiTestScreen_screen_init(void);
lv_obj_t * ui_wifiTestScreen;
lv_obj_t * ui_wifiTestLabel;


// SCREEN: ui_WifiApMode
void ui_WifiApMode_screen_init(void);
lv_obj_t * ui_WifiApMode;
lv_obj_t * ui_ipLabelApMode;
void ui_event_closeWifiServerButtonApMode(lv_event_t * e);
lv_obj_t * ui_closeWifiServerButtonApMode;
lv_obj_t * ui_closeWifiServerLabelApMode;
void ui_event_TurnOffScreenButton1(lv_event_t * e);
lv_obj_t * ui_TurnOffScreenButton1;
lv_obj_t * ui_Label6;


// SCREEN: ui_WifiStaMode
void ui_WifiStaMode_screen_init(void);
lv_obj_t * ui_WifiStaMode;
lv_obj_t * ui_ipLabelStaMode;
void ui_event_closeWifiServerButtonApStaMode(lv_event_t * e);
lv_obj_t * ui_closeWifiServerButtonApStaMode;
lv_obj_t * ui_closeWifiServerLabelStaMode;
void ui_event_TurnOffScreenButton3(lv_event_t * e);
lv_obj_t * ui_TurnOffScreenButton3;
lv_obj_t * ui_Label8;


// SCREEN: ui_bluetoothMode
void ui_bluetoothMode_screen_init(void);
lv_obj_t * ui_bluetoothMode;
void ui_event_returnFromBluetoothModeButton(lv_event_t * e);
lv_obj_t * ui_returnFromBluetoothModeButton;
lv_obj_t * ui_xlabelBluetoothPage;
lv_obj_t * ui_bluetoothPromptMessage;


// SCREEN: ui_SleepScreen
void ui_SleepScreen_screen_init(void);
lv_obj_t * ui_SleepScreen;
lv_obj_t * ui_Button2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void StartAnimation_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnCount(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PHReaderMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_PHReaderMainScreen_screen_init);
        loadDataButtonEvent(e);
    }
}
void ui_event_configWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_configWifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_configWifiScreen_screen_init);
        wifiScanButtonEvent(e);
    }
}
void ui_event_calibrateProbePageButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibratePhScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_CalibratePhScreen_screen_init);
    }
}
void ui_event_highPointCalButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        highPointCalButtonEvent(e);
    }
}
void ui_event_lowPointCalButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        lowPointCalButtonEvent(e);
    }
}
void ui_event_midPointCalButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        midPointCalButtonEvent(e);
    }
}
void ui_event_beginCalButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        beginCalButtonEvent(e);
    }
}
void ui_event_passwordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard,  ui_passwordTextArea);
    }
}
void ui_event_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        wifiTestButtonEvent(e);
        _ui_screen_change(&ui_wifiTestScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_wifiTestScreen_screen_init);
    }
}
void ui_event_setWifiInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_wifiTestScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_wifiTestScreen_screen_init);
        wifiTestButtonEvent(e);
    }
}
void ui_event_RefreshScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        wifiScanButtonEvent(e);
    }
}
void ui_event_tempUnitsSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateTempUnitsSwitchEvent(e);
    }
}
void ui_event_ReturnToHomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        resetDeviceButtonEvent(e);
    }
}
void ui_event_TurnOffScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SleepScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_SleepScreen_screen_init);
        screenOffButtonEvent(e);
    }
}
void ui_event_startWebpageButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_APorSTAScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_APorSTAScreen_screen_init);
    }
}
void ui_event_plotTimePeriodDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setPlotTimePeriodDropdownEvent(e);
    }
}
void ui_event_samplingIntervalDropdown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setSamplingIntervalDropdownEvent(e);
    }
}
void ui_event_startBluetoothButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_bluetoothMode, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_bluetoothMode_screen_init);
        startBluetoothButtonEvent(e);
    }
}
void ui_event_apMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiStaMode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiStaMode_screen_init);
        startWifiStaPageButtonEvent(e);
    }
}
void ui_event_staMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiApMode, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiApMode_screen_init);
        startWifiApPageButtonEvent(e);
    }
}
void ui_event_closeWifiServerButtonApMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PHReaderMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_PHReaderMainScreen_screen_init);
        closeWifiServerButtonEvent(e);
    }
}
void ui_event_TurnOffScreenButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SleepScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_SleepScreen_screen_init);
        screenOffButtonEvent(e);
    }
}
void ui_event_closeWifiServerButtonApStaMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PHReaderMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_PHReaderMainScreen_screen_init);
        closeWifiServerButtonEvent(e);
    }
}
void ui_event_TurnOffScreenButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SleepScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_SleepScreen_screen_init);
        screenOffButtonEvent(e);
    }
}
void ui_event_returnFromBluetoothModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        closeBluetoothButtonEvent(e);
        _ui_screen_change(&ui_PHReaderMainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PHReaderMainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_EntranceScreen_screen_init();
    ui_CalibratePhScreen_screen_init();
    ui_configWifiScreen_screen_init();
    ui_PHReaderMainScreen_screen_init();
    ui_APorSTAScreen_screen_init();
    ui_wifiTestScreen_screen_init();
    ui_WifiApMode_screen_init();
    ui_WifiStaMode_screen_init();
    ui_bluetoothMode_screen_init();
    ui_SleepScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_EntranceScreen);
}
