// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loadData(lv_event_t * e);
void wifiSearch(lv_event_t * e);
void highPointCal(lv_event_t * e);
void lowPointCal(lv_event_t * e);
void midPointCal(lv_event_t * e);
void beginCal(lv_event_t * e);
void wifiTest(lv_event_t * e);
void updateTempUnits(lv_event_t * e);
void setPlotTimePeriod(lv_event_t * e);
void setSamplingInterval(lv_event_t * e);
void startBluetooth(lv_event_t * e);
void startWifiStaPage(lv_event_t * e);
void startWifiApPage(lv_event_t * e);
void closeWifiServerEvent(lv_event_t * e);
void closeBluetooth(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
