// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_bluetoothMode_screen_init(void)
{
    ui_bluetoothMode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_bluetoothMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_returnFromBluetoothModeButton = lv_btn_create(ui_bluetoothMode);
    lv_obj_set_width(ui_returnFromBluetoothModeButton, 50);
    lv_obj_set_height(ui_returnFromBluetoothModeButton, 50);
    lv_obj_set_x(ui_returnFromBluetoothModeButton, 123);
    lv_obj_set_y(ui_returnFromBluetoothModeButton, -83);
    lv_obj_set_align(ui_returnFromBluetoothModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnFromBluetoothModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnFromBluetoothModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnFromBluetoothModeButton, lv_color_hex(0xC10B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnFromBluetoothModeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_xlabelBluetoothPage = lv_label_create(ui_returnFromBluetoothModeButton);
    lv_obj_set_width(ui_xlabelBluetoothPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_xlabelBluetoothPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_xlabelBluetoothPage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_xlabelBluetoothPage, "X");
    lv_obj_set_style_text_font(ui_xlabelBluetoothPage, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bluetoothPromptMessage = lv_label_create(ui_bluetoothMode);
    lv_obj_set_width(ui_bluetoothPromptMessage, lv_pct(95));
    lv_obj_set_height(ui_bluetoothPromptMessage, lv_pct(60));
    lv_obj_set_x(ui_bluetoothPromptMessage, 0);
    lv_obj_set_y(ui_bluetoothPromptMessage, 24);
    lv_obj_set_align(ui_bluetoothPromptMessage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bluetoothPromptMessage, "Please connect to the PHSensor in your bluetooth settings.");
    lv_obj_set_style_text_align(ui_bluetoothPromptMessage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bluetoothPromptMessage, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnFromBluetoothModeButton, ui_event_returnFromBluetoothModeButton, LV_EVENT_ALL, NULL);

}
