// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_EntranceScreen_screen_init(void)
{
    ui_EntranceScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_EntranceScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnCount = lv_btn_create(ui_EntranceScreen);
    lv_obj_set_width(ui_btnCount, 280);
    lv_obj_set_height(ui_btnCount, 55);
    lv_obj_set_x(ui_btnCount, 0);
    lv_obj_set_y(ui_btnCount, lv_pct(31));
    lv_obj_set_align(ui_btnCount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnCount, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnCount, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCount, lv_color_hex(0x07F725), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblButton = lv_label_create(ui_btnCount);
    lv_obj_set_width(ui_lblButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton, "Start PH Reader");
    lv_obj_set_style_text_font(ui_lblButton, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configWifi = lv_btn_create(ui_EntranceScreen);
    lv_obj_set_width(ui_configWifi, 280);
    lv_obj_set_height(ui_configWifi, 55);
    lv_obj_set_x(ui_configWifi, 0);
    lv_obj_set_y(ui_configWifi, lv_pct(-31));
    lv_obj_set_align(ui_configWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton2 = lv_label_create(ui_configWifi);
    lv_obj_set_width(ui_lblButton2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton2, "Start WiFi Config");
    lv_obj_set_style_text_font(ui_lblButton2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrateProbePageButton = lv_btn_create(ui_EntranceScreen);
    lv_obj_set_width(ui_calibrateProbePageButton, 280);
    lv_obj_set_height(ui_calibrateProbePageButton, 55);
    lv_obj_set_align(ui_calibrateProbePageButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_calibrateProbePageButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_calibrateProbePageButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_calibrateProbePageButton, lv_color_hex(0xF2B90A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_calibrateProbePageButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_calibrateProbeButtonLabel = lv_label_create(ui_calibrateProbePageButton);
    lv_obj_set_width(ui_calibrateProbeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_calibrateProbeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_calibrateProbeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_calibrateProbeButtonLabel, "Calibrate PH Probe");
    lv_obj_set_style_text_font(ui_calibrateProbeButtonLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnCount, ui_event_btnCount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configWifi, ui_event_configWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_calibrateProbePageButton, ui_event_calibrateProbePageButton, LV_EVENT_ALL, NULL);

}
