// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_WifiApMode_screen_init(void)
{
    ui_WifiApMode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiApMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ipLabelApMode = lv_label_create(ui_WifiApMode);
    lv_obj_set_width(ui_ipLabelApMode, lv_pct(90));
    lv_obj_set_height(ui_ipLabelApMode, lv_pct(25));
    lv_obj_set_x(ui_ipLabelApMode, 0);
    lv_obj_set_y(ui_ipLabelApMode, -68);
    lv_obj_set_align(ui_ipLabelApMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipLabelApMode, "Connect to ESPWIFI and\nNavigate to 127.127.127.127\nIn Your Browser");
    lv_obj_set_style_text_align(ui_ipLabelApMode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ipLabelApMode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeWifiServerButtonApMode = lv_btn_create(ui_WifiApMode);
    lv_obj_set_width(ui_closeWifiServerButtonApMode, 276);
    lv_obj_set_height(ui_closeWifiServerButtonApMode, 117);
    lv_obj_set_x(ui_closeWifiServerButtonApMode, 0);
    lv_obj_set_y(ui_closeWifiServerButtonApMode, 35);
    lv_obj_set_align(ui_closeWifiServerButtonApMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_closeWifiServerButtonApMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_closeWifiServerButtonApMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_closeWifiServerLabelApMode = lv_label_create(ui_closeWifiServerButtonApMode);
    lv_obj_set_width(ui_closeWifiServerLabelApMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_closeWifiServerLabelApMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_closeWifiServerLabelApMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_closeWifiServerLabelApMode, "Close Wifi Server");
    lv_obj_set_style_text_font(ui_closeWifiServerLabelApMode, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_closeWifiServerButtonApMode, ui_event_closeWifiServerButtonApMode, LV_EVENT_ALL, NULL);

}
