// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_wifiTestScreen_screen_init(void)
{
    ui_wifiTestScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiTestScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiTestLabel = lv_label_create(ui_wifiTestScreen);
    lv_obj_set_width(ui_wifiTestLabel, lv_pct(95));
    lv_obj_set_height(ui_wifiTestLabel, lv_pct(95));
    lv_obj_set_align(ui_wifiTestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiTestLabel, "");
    lv_obj_set_style_text_align(ui_wifiTestLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_wifiTestLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiTestLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

}
