// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "ui.h"

void loadDataButtonEvent(lv_event_t * e)
{
	// Your code here
}

void wifiScanButtonEvent(lv_event_t * e)
{
	// Your code here
}

void highPointCalButtonEvent(lv_event_t * e)
{
	// Your code here
}

void lowPointCalButtonEvent(lv_event_t * e)
{
	// Your code here
}

void midPointCalButtonEvent(lv_event_t * e)
{
	// Your code here
}

void beginCalButtonEvent(lv_event_t * e)
{
	// Your code here
}

void wifiTestButtonEvent(lv_event_t * e)
{
	// Your code here
}

void updateTempUnitsSwitchEvent(lv_event_t * e)
{
	// Your code here
}

void resetDeviceButtonEvent(lv_event_t * e)
{
	// Your code here
}

void screenOffButtonEvent(lv_event_t * e)
{
	// Your code here
}

void setPlotTimePeriodDropdownEvent(lv_event_t * e)
{
	// Your code here
}

void setSamplingIntervalDropdownEvent(lv_event_t * e)
{
	// Your code here
}

void changePHPlotValuesSliderEvent(lv_event_t * e)
{
	// Your code here
}

void changeTempPlotValuesSliderEvent(lv_event_t * e)
{
	// Your code here
}

void startBluetoothButtonEvent(lv_event_t * e)
{
	// Your code here
}

void startWifiStaPageButtonEvent(lv_event_t * e)
{
	// Your code here
}

void startWifiApPageButtonEvent(lv_event_t * e)
{
	// Your code here
}

void closeWifiServerButtonEvent(lv_event_t * e)
{
	// Your code here
}

void closeBluetoothButtonEvent(lv_event_t * e)
{
	// Your code here
}
