// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_APorSTAScreen_screen_init(void)
{
    ui_APorSTAScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_APorSTAScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apMode = lv_btn_create(ui_APorSTAScreen);
    lv_obj_set_width(ui_apMode, lv_pct(45));
    lv_obj_set_height(ui_apMode, lv_pct(95));
    lv_obj_set_x(ui_apMode, 79);
    lv_obj_set_y(ui_apMode, lv_pct(0));
    lv_obj_set_align(ui_apMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_apMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_apMode);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect to a network");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_staMode = lv_btn_create(ui_APorSTAScreen);
    lv_obj_set_width(ui_staMode, lv_pct(45));
    lv_obj_set_height(ui_staMode, lv_pct(95));
    lv_obj_set_x(ui_staMode, -79);
    lv_obj_set_y(ui_staMode, lv_pct(0));
    lv_obj_set_align(ui_staMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_staMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_staMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_staMode);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Connect to PH Sensor");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_apMode, ui_event_apMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_staMode, ui_event_staMode, LV_EVENT_ALL, NULL);

}
