// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_PHReaderMainScreen_screen_init(void)
{
    ui_PHReaderMainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PHReaderMainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainTabView = lv_tabview_create(ui_PHReaderMainScreen, LV_DIR_TOP, 35);
    lv_obj_set_width(ui_mainTabView, 320);
    lv_obj_set_height(ui_mainTabView, 240);
    lv_obj_set_align(ui_mainTabView, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainTabView, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_pHReader = lv_tabview_add_tab(ui_mainTabView, "PH Read");
    lv_obj_clear_flag(ui_pHReader, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_celciusSwitchLabel = lv_label_create(ui_pHReader);
    lv_obj_set_width(ui_celciusSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_celciusSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_celciusSwitchLabel, 54);
    lv_obj_set_y(ui_celciusSwitchLabel, 80);
    lv_obj_set_align(ui_celciusSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_celciusSwitchLabel, "Celcius");
    lv_obj_set_style_text_color(ui_celciusSwitchLabel, lv_color_hex(0x008CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_celciusSwitchLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fahrenheitSwitchLabel = lv_label_create(ui_pHReader);
    lv_obj_set_width(ui_fahrenheitSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_fahrenheitSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_fahrenheitSwitchLabel, -70);
    lv_obj_set_y(ui_fahrenheitSwitchLabel, 80);
    lv_obj_set_align(ui_fahrenheitSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_fahrenheitSwitchLabel, "Fahrenheit");

    ui_tempUnitsSwitch = lv_switch_create(ui_pHReader);
    lv_obj_set_width(ui_tempUnitsSwitch, 50);
    lv_obj_set_height(ui_tempUnitsSwitch, 25);
    lv_obj_set_x(ui_tempUnitsSwitch, 0);
    lv_obj_set_y(ui_tempUnitsSwitch, 80);
    lv_obj_set_align(ui_tempUnitsSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_tempUnitsSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempUnitsSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_anim_time(ui_tempUnitsSwitch, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempUnitsSwitch, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempUnitsSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_pHReader);
    lv_obj_set_width(ui_Panel1, 308);
    lv_obj_set_height(ui_Panel1, 105);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 7);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempStaticLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_tempStaticLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempStaticLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempStaticLabel, -88);
    lv_obj_set_y(ui_tempStaticLabel, lv_pct(30));
    lv_obj_set_align(ui_tempStaticLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempStaticLabel, "T:");
    lv_obj_set_style_text_font(ui_tempStaticLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pHValLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_pHValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pHValLabel, lv_pct(17));
    lv_obj_set_y(ui_pHValLabel, lv_pct(-30));
    lv_obj_set_align(ui_pHValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pHValLabel, "PH VAL");
    lv_obj_set_style_text_font(ui_pHValLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PHStaticLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_PHStaticLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PHStaticLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PHStaticLabel, -91);
    lv_obj_set_y(ui_PHStaticLabel, lv_pct(-30));
    lv_obj_set_align(ui_PHStaticLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PHStaticLabel, "PH:");
    lv_obj_set_style_text_font(ui_PHStaticLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempValLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_tempValLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempValLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempValLabel, lv_pct(17));
    lv_obj_set_y(ui_tempValLabel, lv_pct(30));
    lv_obj_set_align(ui_tempValLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempValLabel, "T VAL ");
    lv_obj_set_style_text_font(ui_tempValLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReturnToHomeButton = lv_btn_create(ui_pHReader);
    lv_obj_set_width(ui_ReturnToHomeButton, 150);
    lv_obj_set_height(ui_ReturnToHomeButton, 47);
    lv_obj_set_x(ui_ReturnToHomeButton, 79);
    lv_obj_set_y(ui_ReturnToHomeButton, -74);
    lv_obj_set_align(ui_ReturnToHomeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReturnToHomeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReturnToHomeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReturnToHomeButton, lv_color_hex(0xC10B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReturnToHomeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ReturnToHomeButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Return to Home");

    ui_TurnOffScreenButton = lv_btn_create(ui_pHReader);
    lv_obj_set_width(ui_TurnOffScreenButton, 150);
    lv_obj_set_height(ui_TurnOffScreenButton, 47);
    lv_obj_set_x(ui_TurnOffScreenButton, -79);
    lv_obj_set_y(ui_TurnOffScreenButton, -74);
    lv_obj_set_align(ui_TurnOffScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TurnOffScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TurnOffScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_TurnOffScreenButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Turn Off Screen");

    ui_chartTabPage = lv_tabview_add_tab(ui_mainTabView, "Plot");
    lv_obj_clear_flag(ui_chartTabPage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_pHTempChart = lv_chart_create(ui_chartTabPage);
    lv_obj_set_width(ui_pHTempChart, 242);
    lv_obj_set_height(ui_pHTempChart, 162);
    lv_obj_set_x(ui_pHTempChart, 0);
    lv_obj_set_y(ui_pHTempChart, -15);
    lv_obj_set_align(ui_pHTempChart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_pHTempChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_pHTempChart, 15);
    lv_chart_set_range(ui_pHTempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 14);
    lv_chart_set_div_line_count(ui_pHTempChart, 15, 13);
    lv_chart_set_axis_tick(ui_pHTempChart, LV_CHART_AXIS_PRIMARY_X, 7, 5, 7, 2, true, 50);
    lv_chart_set_axis_tick(ui_pHTempChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 3, 7, true, 50);
    lv_chart_set_axis_tick(ui_pHTempChart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 8, 2, true, 25);



    ui_showPHButton = lv_btn_create(ui_chartTabPage);
    lv_obj_set_width(ui_showPHButton, 40);
    lv_obj_set_height(ui_showPHButton, 32);
    lv_obj_set_x(ui_showPHButton, -140);
    lv_obj_set_y(ui_showPHButton, 87);
    lv_obj_set_align(ui_showPHButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_showPHButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_showPHButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_showPHButton, lv_color_hex(0x1F9926), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_showPHButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_showPHButton);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "PH");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_showTempButton = lv_btn_create(ui_chartTabPage);
    lv_obj_set_width(ui_showTempButton, 40);
    lv_obj_set_height(ui_showTempButton, 32);
    lv_obj_set_x(ui_showTempButton, 140);
    lv_obj_set_y(ui_showTempButton, 87);
    lv_obj_set_align(ui_showTempButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_showTempButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_showTempButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_showTempButton, lv_color_hex(0xD40C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_showTempButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_showTempButton);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Temp");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chartUnitLabel = lv_label_create(ui_chartTabPage);
    lv_obj_set_width(ui_chartUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chartUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chartUnitLabel, 0);
    lv_obj_set_y(ui_chartUnitLabel, 94);
    lv_obj_set_align(ui_chartUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chartUnitLabel, "Seconds");
    lv_obj_set_style_text_color(ui_chartUnitLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chartUnitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsTabPage = lv_tabview_add_tab(ui_mainTabView, "Settings");
    lv_obj_clear_flag(ui_settingsTabPage,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_TabView1 = lv_tabview_create(ui_settingsTabPage, LV_DIR_TOP, 35);
    lv_obj_set_width(ui_TabView1, 320);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags


    ui_generalSettingsTabPage = lv_tabview_add_tab(ui_TabView1, "General");
    lv_obj_clear_flag(ui_generalSettingsTabPage,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_plotTimePeriodDropdown = lv_dropdown_create(ui_generalSettingsTabPage);
    lv_dropdown_set_options(ui_plotTimePeriodDropdown,
                            "1 Minute\n5 Minutes\n30 Minutes\n1 Hour\n2 Hours\n24 Hours\n1 Day\n1 Week");
    lv_obj_set_width(ui_plotTimePeriodDropdown, 126);
    lv_obj_set_height(ui_plotTimePeriodDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plotTimePeriodDropdown, 80);
    lv_obj_set_y(ui_plotTimePeriodDropdown, 57);
    lv_obj_set_align(ui_plotTimePeriodDropdown, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_plotTimePeriodDropdown, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_plotTimePeriodDropdown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_plotTimePeriodDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_plotTimePeriodLabel = lv_label_create(ui_generalSettingsTabPage);
    lv_obj_set_width(ui_plotTimePeriodLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_plotTimePeriodLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_plotTimePeriodLabel, -69);
    lv_obj_set_y(ui_plotTimePeriodLabel, 56);
    lv_obj_set_align(ui_plotTimePeriodLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_plotTimePeriodLabel, "Time Period For Plots:");

    ui_staticBatteryLabel = lv_label_create(ui_generalSettingsTabPage);
    lv_obj_set_width(ui_staticBatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_staticBatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staticBatteryLabel, -43);
    lv_obj_set_y(ui_staticBatteryLabel, -68);
    lv_obj_set_align(ui_staticBatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_staticBatteryLabel, "Battery Level, Time Remaining:");
    lv_obj_set_style_border_color(ui_staticBatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_staticBatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_staticBatteryLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_staticBatteryLabel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateBatteryLabel = lv_label_create(ui_generalSettingsTabPage);
    lv_obj_set_width(ui_UpdateBatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpdateBatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UpdateBatteryLabel, 111);
    lv_obj_set_y(ui_UpdateBatteryLabel, -65);
    lv_obj_set_align(ui_UpdateBatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpdateBatteryLabel, "100%\n24:24:60");
    lv_obj_set_style_text_align(ui_UpdateBatteryLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UpdateBatteryLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_plotSettingsTabPage = lv_tabview_add_tab(ui_TabView1, "Plot Settings");
    lv_obj_clear_flag(ui_plotSettingsTabPage,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_TempSlider = lv_slider_create(ui_plotSettingsTabPage);
    lv_slider_set_range(ui_TempSlider, 0, 10000);
    lv_slider_set_mode(ui_TempSlider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_TempSlider, 10000, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TempSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TempSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempSlider, 280);
    lv_obj_set_height(ui_TempSlider, 10);
    lv_obj_set_x(ui_TempSlider, 0);
    lv_obj_set_y(ui_TempSlider, -35);
    lv_obj_set_align(ui_TempSlider, LV_ALIGN_CENTER);


    ui_PHSlider = lv_slider_create(ui_plotSettingsTabPage);
    lv_slider_set_range(ui_PHSlider, 0, 1400);
    lv_slider_set_mode(ui_PHSlider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_PHSlider, 1400, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PHSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PHSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PHSlider, 280);
    lv_obj_set_height(ui_PHSlider, 10);
    lv_obj_set_x(ui_PHSlider, 0);
    lv_obj_set_y(ui_PHSlider, 36);
    lv_obj_set_align(ui_PHSlider, LV_ALIGN_CENTER);


    ui_staticTempRangeLabel = lv_label_create(ui_plotSettingsTabPage);
    lv_obj_set_width(ui_staticTempRangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_staticTempRangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staticTempRangeLabel, -3);
    lv_obj_set_y(ui_staticTempRangeLabel, -60);
    lv_obj_set_align(ui_staticTempRangeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_staticTempRangeLabel, "Tempature Range");

    ui_staticPHRangeLabel = lv_label_create(ui_plotSettingsTabPage);
    lv_obj_set_width(ui_staticPHRangeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_staticPHRangeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_staticPHRangeLabel, -4);
    lv_obj_set_y(ui_staticPHRangeLabel, 12);
    lv_obj_set_align(ui_staticPHRangeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_staticPHRangeLabel, "PH Range");

    ui_phRangeLiveLabel = lv_label_create(ui_plotSettingsTabPage);
    lv_obj_set_width(ui_phRangeLiveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phRangeLiveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phRangeLiveLabel, 0);
    lv_obj_set_y(ui_phRangeLiveLabel, 63);
    lv_obj_set_align(ui_phRangeLiveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_phRangeLiveLabel, "0");

    ui_tempRangeLiveLabel = lv_label_create(ui_plotSettingsTabPage);
    lv_obj_set_width(ui_tempRangeLiveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempRangeLiveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempRangeLiveLabel, 0);
    lv_obj_set_y(ui_tempRangeLiveLabel, -12);
    lv_obj_set_align(ui_tempRangeLiveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempRangeLiveLabel, "0");

    ui_wirelessControlSettingsTabPage = lv_tabview_add_tab(ui_TabView1, "Wireless");
    lv_obj_clear_flag(ui_wirelessControlSettingsTabPage,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_startBluetoothButton = lv_btn_create(ui_wirelessControlSettingsTabPage);
    lv_obj_set_width(ui_startBluetoothButton, 300);
    lv_obj_set_height(ui_startBluetoothButton, 45);
    lv_obj_set_align(ui_startBluetoothButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startBluetoothButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startBluetoothButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startBluetoothButtonLabel = lv_label_create(ui_startBluetoothButton);
    lv_obj_set_width(ui_startBluetoothButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startBluetoothButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startBluetoothButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startBluetoothButtonLabel, "Start Bluetooth");
    lv_obj_set_style_text_font(ui_startBluetoothButtonLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_startWebpageButton = lv_btn_create(ui_wirelessControlSettingsTabPage);
    lv_obj_set_width(ui_startWebpageButton, 300);
    lv_obj_set_height(ui_startWebpageButton, 45);
    lv_obj_set_x(ui_startWebpageButton, 0);
    lv_obj_set_y(ui_startWebpageButton, -52);
    lv_obj_set_align(ui_startWebpageButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_startWebpageButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_startWebpageButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_startWiFiButtonLabel = lv_label_create(ui_startWebpageButton);
    lv_obj_set_width(ui_startWiFiButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_startWiFiButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_startWiFiButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_startWiFiButtonLabel, "Start Webpage");
    lv_obj_set_style_text_font(ui_startWiFiButtonLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_configWifi2 = lv_btn_create(ui_wirelessControlSettingsTabPage);
    lv_obj_set_width(ui_configWifi2, 300);
    lv_obj_set_height(ui_configWifi2, 45);
    lv_obj_set_x(ui_configWifi2, 0);
    lv_obj_set_y(ui_configWifi2, 52);
    lv_obj_set_align(ui_configWifi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_configWifi2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_configWifi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblButton3 = lv_label_create(ui_configWifi2);
    lv_obj_set_width(ui_lblButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblButton3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblButton3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblButton3, "Start WiFi Config");
    lv_obj_set_style_text_font(ui_lblButton3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tempUnitsSwitch, ui_event_tempUnitsSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ReturnToHomeButton, ui_event_ReturnToHomeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TurnOffScreenButton, ui_event_TurnOffScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_plotTimePeriodDropdown, ui_event_plotTimePeriodDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempSlider, ui_event_TempSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PHSlider, ui_event_PHSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startBluetoothButton, ui_event_startBluetoothButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_startWebpageButton, ui_event_startWebpageButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_configWifi2, ui_event_configWifi2, LV_EVENT_ALL, NULL);

}
