// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PHReaderWifiV1

#include "../ui.h"

void ui_WifiStaMode_screen_init(void)
{
    ui_WifiStaMode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiStaMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ipLabelStaMode = lv_label_create(ui_WifiStaMode);
    lv_obj_set_width(ui_ipLabelStaMode, lv_pct(90));
    lv_obj_set_height(ui_ipLabelStaMode, lv_pct(25));
    lv_obj_set_x(ui_ipLabelStaMode, 0);
    lv_obj_set_y(ui_ipLabelStaMode, -47);
    lv_obj_set_align(ui_ipLabelStaMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ipLabelStaMode, "Connect to SSID and\nNavigate to 127.127.127.127\nIn Your Browser");
    lv_obj_set_style_text_align(ui_ipLabelStaMode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ipLabelStaMode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeWifiServerButtonApStaMode = lv_btn_create(ui_WifiStaMode);
    lv_obj_set_width(ui_closeWifiServerButtonApStaMode, 292);
    lv_obj_set_height(ui_closeWifiServerButtonApStaMode, 117);
    lv_obj_set_x(ui_closeWifiServerButtonApStaMode, 0);
    lv_obj_set_y(ui_closeWifiServerButtonApStaMode, 48);
    lv_obj_set_align(ui_closeWifiServerButtonApStaMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_closeWifiServerButtonApStaMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_closeWifiServerButtonApStaMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_closeWifiServerButtonApStaMode, lv_color_hex(0x34C6C5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_closeWifiServerButtonApStaMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_closeWifiServerButtonApStaMode, lv_color_hex(0x0A3383),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_closeWifiServerButtonApStaMode, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_closeWifiServerLabelStaMode = lv_label_create(ui_closeWifiServerButtonApStaMode);
    lv_obj_set_width(ui_closeWifiServerLabelStaMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_closeWifiServerLabelStaMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_closeWifiServerLabelStaMode, LV_ALIGN_CENTER);
    lv_label_set_text(ui_closeWifiServerLabelStaMode, "Close Wifi Server");
    lv_obj_set_style_text_font(ui_closeWifiServerLabelStaMode, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TurnOffScreenButton3 = lv_btn_create(ui_WifiStaMode);
    lv_obj_set_width(ui_TurnOffScreenButton3, 310);
    lv_obj_set_height(ui_TurnOffScreenButton3, 35);
    lv_obj_set_x(ui_TurnOffScreenButton3, 0);
    lv_obj_set_y(ui_TurnOffScreenButton3, -98);
    lv_obj_set_align(ui_TurnOffScreenButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TurnOffScreenButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TurnOffScreenButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_TurnOffScreenButton3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Turn Off Screen");

    lv_obj_add_event_cb(ui_closeWifiServerButtonApStaMode, ui_event_closeWifiServerButtonApStaMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TurnOffScreenButton3, ui_event_TurnOffScreenButton3, LV_EVENT_ALL, NULL);

}
